### ISSUE TITLE
Sooooo many errors.

### ISSUE THREAD

**Issue by binbandit** [wiyarmir/minigdxcraft#1] opened 2016-01-28 20:43 UTC
Hey can you please help me, as there are so many errors.

**Comment by wiyarmir** [comment] 2016-01-29 00:11
Could you be more specific? As you can see, code is 3 years old.

**Comment by binbandit** [comment] 2016-01-29 05:19
yeah, the age of the code doesn't mean anything... before you upload code, it should be error free... and if not, you should tell people how to fix those said errors.

**Comment by binbandit** [comment] 2016-01-29 05:25
http://imgur.com/gvZEiTA

link to the pic with every error

**Comment by wiyarmir** [comment] 2016-01-29 09:43
Let's keep things clear: **I am not here for producing error free code for you at your will.**

I stopped being interested in this code 3 years ago.

The way this works is, if you are so interested on this, you figure out what's going on and either:
- Gather information and give a real bug report. No, a screenshot of Eclipse errors is not a bug report.
- Open a pull request with a proper description of the changes, and you are added as contributor.
- Create a fork and do your own error free code telling everybody how to fix all errors of the world.

You can find more information in this lovely link:

http://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/

Or just googling. I will close this one, and hope all this information has been useful and helps you creating better issues in the future.

Have a nice day!

**Comment by wiyarmir** [comment] 2016-01-29 09:49
closed #1

**Closed as completed** 2016-01-29 11:20 UTC
Labels: invalid
